// constants/missions.js
export const DEFAULT_MISSIONS = [
  // ========== DAILY MISSIONS ==========
  {
    id: 1,
    title: "Log your first craving",
    description: "Track a craving to understand your triggers",
    type: "craving-first",
    completed: false,
    icon: "🎯",
    xp: 50,
    category: "daily",
  },
  {
    id: 2,
    title: "Write in your journal",
    description: "Share your thoughts and feelings",
    type: "journal-first",
    completed: false,
    icon: "📝",
    xp: 30,
    category: "daily",
  },
  {
    id: 3,
    title: "Track your mood",
    description: "Log how you're feeling today",
    type: "mood-first",
    completed: false,
    icon: "😊",
    xp: 25,
    category: "daily",
  },
  {
    id: 4,
    title: "Chat with AI support",
    description: "Get personalized guidance",
    type: "ai-first",
    completed: false,
    icon: "✨",
    xp: 40,
    category: "daily",
  },
  {
    id: 5,
    title: "Morning check-in",
    description: "Start your day with intention",
    type: "journal-morning",
    completed: false,
    icon: "🌅",
    xp: 35,
    category: "daily",
  },
  {
    id: 6,
    title: "Evening reflection",
    description: "End your day with gratitude",
    type: "journal-evening",
    completed: false,
    icon: "🌙",
    xp: 35,
    category: "daily",
  },
  {
    id: 7,
    title: "Overcome a craving today",
    description: "Stay strong when temptation hits",
    type: "craving-daily",
    completed: false,
    icon: "💪",
    xp: 60,
    category: "daily",
  },
  {
    id: 8,
    title: "Positive affirmation",
    description: "Write one positive thing about yourself",
    type: "journal-affirmation",
    completed: false,
    icon: "🌟",
    xp: 30,
    category: "daily",
  },

  // ========== WEEKLY CHALLENGES ==========
  {
    id: 9,
    title: "Overcome 3 cravings",
    description: "Resist 3 cravings",
    type: "craving-count",
    target: 3,
    progress: 0,
    completed: false,
    icon: "💪",
    xp: 100,
    category: "weekly",
  },
  {
    id: 10,
    title: "7 day streak",
    description: "Stay clean for one week",
    type: "streak",
    target: 7,
    completed: false,
    icon: "🔥",
    xp: 200,
    category: "weekly",
  },
  {
    id: 11,
    title: "Journal 5 times",
    description: "Write 5 journal entries",
    type: "journal-count",
    target: 5,
    progress: 0,
    completed: false,
    icon: "📖",
    xp: 150,
    category: "weekly",
  },
  {
    id: 12,
    title: "Overcome 10 cravings",
    description: "Build your resistance muscle",
    type: "craving-count",
    target: 10,
    progress: 0,
    completed: false,
    icon: "🛡️",
    xp: 250,
    category: "weekly",
  },
  {
    id: 13,
    title: "Track mood daily",
    description: "Log your mood 7 times",
    type: "mood-count",
    target: 7,
    progress: 0,
    completed: false,
    icon: "📊",
    xp: 120,
    category: "weekly",
  },
  {
    id: 14,
    title: "Early bird week",
    description: "Morning check-in 7 days in a row",
    type: "morning-streak",
    target: 7,
    progress: 0,
    completed: false,
    icon: "☀️",
    xp: 180,
    category: "weekly",
  },
  {
    id: 15,
    title: "Night owl week",
    description: "Evening reflection 7 nights in a row",
    type: "evening-streak",
    target: 7,
    progress: 0,
    completed: false,
    icon: "🌙",
    xp: 180,
    category: "weekly",
  },
  {
    id: 16,
    title: "Perfect week",
    description: "Stay clean for 7 days, resisting every craving you log",
    type: "perfect-week",
    target: 7,
    progress: 0,
    completed: false,
    icon: "🎯",
    xp: 300,
    category: "weekly",
  },
  {
    id: 17,
    title: "AI wisdom seeker",
    description: "Talk to the AI coach 7 times",
    type: "ai-count",
    target: 7,
    progress: 0,
    completed: false,
    icon: "🧠",
    xp: 140,
    category: "weekly",
  },
  {
    id: 18,
    title: "Two week warrior",
    description: "Stay clean for 14 consecutive days",
    type: "streak",
    target: 14,
    completed: false,
    icon: "⚔️",
    xp: 350,
    category: "weekly",
  },

  // ========== MONTHLY GOALS ==========
  {
    id: 19,
    title: "30 day champion",
    description: "Complete one full month clean",
    type: "streak",
    target: 30,
    completed: false,
    icon: "🏆",
    xp: 500,
    category: "monthly",
  },
  {
    id: 20,
    title: "Overcome 50 cravings",
    description: "Resist 50 cravings and master your triggers",
    type: "craving-count",
    target: 50,
    progress: 0,
    completed: false,
    icon: "⚡",
    xp: 600,
    category: "monthly",
  },
  {
    id: 21,
    title: "Journal master",
    description: "Write 30 journal entries",
    type: "journal-count",
    target: 30,
    progress: 0,
    completed: false,
    icon: "✍️",
    xp: 400,
    category: "monthly",
  },
  {
    id: 22,
    title: "Support seeker",
    description: "Use AI support 20 times",
    type: "ai-count",
    target: 20,
    progress: 0,
    completed: false,
    icon: "🤝",
    xp: 350,
    category: "monthly",
  },
  {
    id: 23,
    title: "Mood tracker pro",
    description: "Track your mood for 30 days straight",
    type: "mood-count",
    target: 30,
    progress: 0,
    completed: false,
    icon: "🎭",
    xp: 450,
    category: "monthly",
  },
  {
    id: 24,
    title: "No relapse month",
    description: "30 days without giving in to a single craving",
    type: "perfect-month",
    target: 30,
    progress: 0,
    completed: false,
    icon: "🛡️",
    xp: 700,
    category: "monthly",
  },
  {
    id: 25,
    title: "45 day milestone",
    description: "Six weeks of transformation",
    type: "streak",
    target: 45,
    completed: false,
    icon: "💎",
    xp: 650,
    category: "monthly",
  },
  {
    id: 26,
    title: "60 day hero",
    description: "Two months of dedication",
    type: "streak",
    target: 60,
    completed: false,
    icon: "🦸",
    xp: 800,
    category: "monthly",
  },
  {
    id: 27,
    title: "Overcome 100 cravings",
    description: "Century of victories",
    type: "craving-count",
    target: 100,
    progress: 0,
    completed: false,
    icon: "💯",
    xp: 900,
    category: "monthly",
  },

  // ========== QUARTERLY ACHIEVEMENTS ==========
  {
    id: 28,
    title: "90 days strong",
    description: "Three months of freedom",
    type: "streak",
    target: 90,
    completed: false,
    icon: "🚀",
    xp: 1000,
    category: "milestone",
  },
  {
    id: 29,
    title: "Quarter year warrior",
    description: "100 days of transformation",
    type: "streak",
    target: 100,
    completed: false,
    icon: "⭐",
    xp: 1200,
    category: "milestone",
  },
  {
    id: 30,
    title: "Craving crusher",
    description: "Overcome 150 cravings",
    type: "craving-count",
    target: 150,
    progress: 0,
    completed: false,
    icon: "⚔️",
    xp: 1300,
    category: "milestone",
  },
  {
    id: 31,
    title: "Journal enthusiast",
    description: "Write 100 journal entries",
    type: "journal-count",
    target: 100,
    progress: 0,
    completed: false,
    icon: "📚",
    xp: 800,
    category: "milestone",
  },
  {
    id: 32,
    title: "Mood master",
    description: "Track mood for 90 consecutive days",
    type: "mood-count",
    target: 90,
    progress: 0,
    completed: false,
    icon: "🎨",
    xp: 900,
    category: "milestone",
  },

  // ========== HALF YEAR MILESTONES ==========
  {
    id: 33,
    title: "6 month warrior",
    description: "Half a year of transformation",
    type: "streak",
    target: 180,
    completed: false,
    icon: "👑",
    xp: 2000,
    category: "milestone",
  },
  {
    id: 34,
    title: "200 day legend",
    description: "200 consecutive days clean",
    type: "streak",
    target: 200,
    completed: false,
    icon: "🌟",
    xp: 2200,
    category: "milestone",
  },
  {
    id: 35,
    title: "Craving annihilator",
    description: "Overcome 300 cravings",
    type: "craving-count",
    target: 300,
    progress: 0,
    completed: false,
    icon: "🗡️",
    xp: 2500,
    category: "milestone",
  },
  {
    id: 36,
    title: "Support champion",
    description: "Use AI support 100 times",
    type: "ai-count",
    target: 100,
    progress: 0,
    completed: false,
    icon: "🌈",
    xp: 1500,
    category: "milestone",
  },
  {
    id: 37,
    title: "Journal devotee",
    description: "Write 200 journal entries",
    type: "journal-count",
    target: 200,
    progress: 0,
    completed: false,
    icon: "📖",
    xp: 1800,
    category: "milestone",
  },

  // ========== ONE YEAR ACHIEVEMENTS ==========
  {
    id: 38,
    title: "One year legend",
    description: "A full year of recovery",
    type: "streak",
    target: 365,
    completed: false,
    icon: "💎",
    xp: 5000,
    category: "milestone",
  },
  {
    id: 39,
    title: "300 day titan",
    description: "Nearly a year strong",
    type: "streak",
    target: 300,
    completed: false,
    icon: "🏔️",
    xp: 3000,
    category: "milestone",
  },
  {
    id: 40,
    title: "Craving master",
    description: "Overcome 500 cravings",
    type: "craving-count",
    target: 500,
    progress: 0,
    completed: false,
    icon: "🛡️",
    xp: 4000,
    category: "milestone",
  },
  {
    id: 41,
    title: "Journal master",
    description: "Write 365 journal entries - one for each day",
    type: "journal-count",
    target: 365,
    progress: 0,
    completed: false,
    icon: "📕",
    xp: 3500,
    category: "milestone",
  },
  {
    id: 42,
    title: "Year of awareness",
    description: "Track mood for 365 days",
    type: "mood-count",
    target: 365,
    progress: 0,
    completed: false,
    icon: "🎭",
    xp: 3500,
    category: "milestone",
  },

  // ========== EXTENDED MILESTONES ==========
  {
    id: 43,
    title: "18 month titan",
    description: "Life transformation complete",
    type: "streak",
    target: 547,
    completed: false,
    icon: "🏔️",
    xp: 7500,
    category: "milestone",
  },
  {
    id: 44,
    title: "500 day hero",
    description: "500 consecutive days of freedom",
    type: "streak",
    target: 500,
    completed: false,
    icon: "🦸",
    xp: 6000,
    category: "milestone",
  },
  {
    id: 45,
    title: "2 year champion",
    description: "Two years of freedom",
    type: "streak",
    target: 730,
    completed: false,
    icon: "🌟",
    xp: 10000,
    category: "milestone",
  },
  {
    id: 46,
    title: "Craving destroyer",
    description: "Overcome 1000 cravings",
    type: "craving-count",
    target: 1000,
    progress: 0,
    completed: false,
    icon: "⚡",
    xp: 8000,
    category: "milestone",
  },
  {
    id: 47,
    title: "2.5 year warrior",
    description: "30 months of dedication",
    type: "streak",
    target: 912,
    completed: false,
    icon: "👑",
    xp: 12000,
    category: "milestone",
  },
  {
    id: 48,
    title: "3 year master",
    description: "Complete mastery achieved",
    type: "streak",
    target: 1095,
    completed: false,
    icon: "⭐",
    xp: 15000,
    category: "milestone",
  },
  {
    id: 49,
    title: "1000 day legend",
    description: "1000 consecutive days clean",
    type: "streak",
    target: 1000,
    completed: false,
    icon: "💯",
    xp: 13000,
    category: "milestone",
  },
  {
    id: 50,
    title: "Craving eliminator",
    description: "Overcome 2000 cravings",
    type: "craving-count",
    target: 2000,
    progress: 0,
    completed: false,
    icon: "🗡️",
    xp: 15000,
    category: "milestone",
  },

  // ========== LONG-TERM MASTERY ==========
  {
    id: 51,
    title: "4 year legend",
    description: "Four years of transformation",
    type: "streak",
    target: 1460,
    completed: false,
    icon: "🏆",
    xp: 20000,
    category: "milestone",
  },
  {
    id: 52,
    title: "5 year legend",
    description: "Elite recovery status",
    type: "streak",
    target: 1825,
    completed: false,
    icon: "🔥",
    xp: 25000,
    category: "milestone",
  },
  {
    id: 53,
    title: "2000 day titan",
    description: "Over 5 years of freedom",
    type: "streak",
    target: 2000,
    completed: false,
    icon: "🌟",
    xp: 30000,
    category: "milestone",
  },
  {
    id: 54,
    title: "7 year master",
    description: "Seven years of excellence",
    type: "streak",
    target: 2555,
    completed: false,
    icon: "👑",
    xp: 35000,
    category: "milestone",
  },
  {
    id: 55,
    title: "Decade of freedom",
    description: "10 years clean - legendary status",
    type: "streak",
    target: 3650,
    completed: false,
    icon: "💎",
    xp: 50000,
    category: "milestone",
  },
  {
    id: 56,
    title: "Ultimate warrior",
    description: "Overcome 5000 cravings",
    type: "craving-count",
    target: 5000,
    progress: 0,
    completed: false,
    icon: "⚔️",
    xp: 40000,
    category: "milestone",
  },
  {
    id: 57,
    title: "Journal legend",
    description: "Write 1000 journal entries",
    type: "journal-count",
    target: 1000,
    progress: 0,
    completed: false,
    icon: "📚",
    xp: 20000,
    category: "milestone",
  },
  {
    id: 58,
    title: "Wisdom master",
    description: "Use AI support 500 times",
    type: "ai-count",
    target: 500,
    progress: 0,
    completed: false,
    icon: "🧠",
    xp: 15000,
    category: "milestone",
  },
];
